For test
RONYN52/forSwift pull request #1
Opened 2020-10-27 17:27 UTC by RONYN52

Убрал лишнее

2020-10-27 18:54 UTC, jsyrtsov requested changes

2020-10-27 18:54 UTC, jsyrtsov commented on tableTest/Services/LoadData.swift
>      override func awakeFromNib() {
зачем пустой метод

2020-10-27 18:54 UTC, jsyrtsov commented on tableTest/Services/LoadData.swift
>      }
зачем пустой метод

2020-10-28 07:18 UTC, jsyrtsov requested changes

2020-10-28 07:18 UTC, jsyrtsov commented on tableTest/Enums/URLs.swift
> +import Foundation
добавь пустую строчку после import'ов

2020-10-28 07:18 UTC, jsyrtsov commented on tableTest/Services/NetworkService.swift
> +   URLSession.shared.dataTask(with: url) { (data, respons, error) in
неправильный отступ

2020-10-28 07:18 UTC, jsyrtsov commented on tableTest/ViewController.swift
>      }
пустой метод

2020-10-28 07:18 UTC, jsyrtsov commented on tableTest/ViewController.swift
> +        textOut.text = ""
private

2020-10-28 07:22 UTC, RONYN52 commented on tableTest/ViewController.swift
> +        textOut.text = ""
не сделал privat, потому что пока не разобрался как работает)

2020-10-28 07:31 UTC, jsyrtsov requested changes

2020-10-28 07:31 UTC, jsyrtsov commented on tableTest/Models/UserData.swift
> +import Foundation
здесь тоже

2020-10-28 07:31 UTC, jsyrtsov commented on tableTest/Services/NetworkService.swift
> +           guard let _ = result.id else {
зачем здесь Guard 
зачем здесь создавать переменную ?

2020-10-28 11:28 UTC, jsyrtsov approved these changes

2020-10-28 11:28 UTC, jsyrtsov commented on tableTest/Services/NetworkService.swift
> +            do  {
после do лишний пробел и после catch

2020-11-01 19:31 UTC, jsyrtsov approved these changes

2020-11-01 19:31 UTC, jsyrtsov commented on tableTest/Services/NetworkService.swift
>                      completion(result.self)
можно просто result, без self

2020-11-01 19:32 UTC, merged